[package]
name = "smol-mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
aes = "0.8.3"
ctr = "0.9.2"
katex-doc = "0.1.0"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "docs/katex-header.html" ]